# Use the official Nginx image as the base image
FROM nginx:alpine

ENV BACKEND_URL=backend-service:5000
#ENV BACKEND_URL=backend-service:30007
# Copy the frontend templates to the Nginx HTML directory
COPY ./templates /usr/share/nginx/html

# Nginx will automatically serve static files
