namespace: ms-final

frontend:
  replicas: 1
  image:
    repository: deepakchandmarthala/ms-final
    tag: frontend-v2
  service:
    type: LoadBalancer
    port: 80
  config:
    backendUrl: "http://backend-service.ms-final.svc.cluster.local:5000"

backend:
  replicas: 1
  image:
    repository: deepakchandmarthala/ms-final
    tag: backend
  service:
    type: NodePort
    port: 5000
  env:
    flaskEnv: "production"
