version: '3.8'

services:
  backend:
    image: ms-final-backend
    build:
      context: ./backend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: ms-final-frontend
    build:
      context: ./frontend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
