version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-back
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-front
    container_name: frontend
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
