apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: {{ .Values.namespace }}
data:
  BACKEND_URL: "{{ .Values.frontend.config.backendUrl }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        envFrom:
          - configMapRef:
              name: frontend-configmap
        ports:
        - containerPort: 80
