apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ms-final
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodeport: 30007
  type: NodePort
