apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ms-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: deepakchandmarthala/ms-final:backend
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"