apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ms-final
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodeport: 30007
  type: LoadBalancer  
